version: '3'
services:
  api:
    build: ./api
    restart: always
    deploy:
      resources:
        limits:            # limite máximo de recursos
          cpus: '0.50'
          memory: 2048M
        reservations:      # definida como a quantidade mínima para a execução
          cpus: '0.50'
          memory: 1042M
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 2048M
        reservations:
          cpus: '0.50'
          memory: 1042M
    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: api_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/data:/var/lib/postgresql/data
  frontend:
    build: ./frontend
    restart: always
    deploy:
      resources:
        limits:            # limite máximo de recursos
          cpus: '1.0'
          memory: 2048M
        reservations:      # definida como a quantidade mínima para a execução
          cpus: '1.0'
          memory: 1042M
    ports:
      - "3000:3000"
    depends_on:
      - api
